### PR TITLE
Updates for istio 1.0.0 release

### PR DESCRIPTION
**Pull request by erkolson**
- Accounts for changes in virtual services/route rules.
- Removes some dead code.

### CODE REVIEW

**Comment by erkolson** [comment]
My github account has an @google email address associated and that email address is recorded as the author of the commit.  Not sure what is wrong.

**Comment by chrislovecnm** [comment]
@robinpercy yes this is WIP until istio fix goes in

**Comment by chrislovecnm** [comment]
cc @samuelmi2

**Comment by chrislovecnm** [comment]
closing as we are doing 1.0.1

**Pull request closed without merging**
